### ISSUE TITLE
Compatibility with Machine Vision SDK v1.1.9

### ISSUE THREAD

**Issue by hoangthien94** [ATLFlight/ros-examples#13]
Hi. When I try to build with [Machine Vision SDK v1.1.9](https://developer.qualcomm.com/software/machine-vision-sdk/tools), I got this error:

```
[ 14%] Building CXX object snap_ros_examples/CMakeFiles/snap_vislam.dir/src/camera/SnapdragonCameraManager.cpp.o                                                                                              
/home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp: In member function 'int32_t Snapdragon::CameraManager::Initialize()':
/home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp:142:43: error: 'struct mvCPA_Configuration' has no member named 'startExposure'
     snap_camera_param_ptr_->mv_cpa_config.startExposure = camera_config_ptr_->exposure;
                                           ^
/home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp:143:43: error: 'struct mvCPA_Configuration' has no member named 'startGain'
     snap_camera_param_ptr_->mv_cpa_config.startGain = camera_config_ptr_->gain;
                                           ^
/home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp: In member function 'void Snapdragon::CameraManager::UpdateGainAndExposure()':
/home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp:225:40: error: too many arguments to function 'void mvCPA_AddFrame(mvCPA*, const uint8_t*, uint32_t)'
       camera_config_ptr_->memory_stride);
                                        ^
In file included from /home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraTypes.hpp:36:0,
                 from /home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.hpp:46,
                 from /home/linaro/ros_ws/src/snap_ros_examples/src/camera/SnapdragonCameraManager.cpp:32:
/usr/include/mv/mvCPA.h:242:16: note: declared here
    MV_API void mvCPA_AddFrame( mvCPA* pObj, const uint8_t* pixels,
                ^
make[3]: *** [snap_ros_examples/CMakeFiles/snap_vislam.dir/src/camera/SnapdragonCameraManager.cpp.o] Error 1
make[2]: *** [snap_ros_examples/CMakeFiles/snap_vislam.dir/all] Error 2
make[1]: *** [snap_ros_examples/CMakeFiles/snap_vislam_node.dir/rule] Error 2
make: *** [snap_vislam_node] Error 2
make: INTERNAL: Exiting with 6 jobserver tokens available; should be 4!
Invoking "make snap_vislam_node -j4 -l4" failed
```

I guess this is because there is a mismatch between the version of Machine Vision SDK that I have installed and what the example expects? I had successfully built and tested it with `mv_0.9.1` before I tried with `mv_1.1.9`.

Can this example be used with later versions of Machine Vision SDK, in particular `mv_1.1.9`?

**Comment by ericjohnson97** [comment]
@hoangthien94, I went down the rabbit hole suggested by potaito. Unfortunately, I couldn't fix everything to get to compile. 
The errors you had can be easily fixed by changing:
`mvCPA_AddFrame(mvCPA_ptr_, 
      frame_queue_[frame_q_write_index_].second->data,
      camera_config_ptr_->pixel_width,
      camera_config_ptr_->pixel_height,
      camera_config_ptr_->memory_stride);`
into:
mvCPA_AddFrame(mvCPA_ptr_, 
      frame_queue_[frame_q_write_index_].second->data,
      camera_config_ptr_->memory_stride);
Still, this doesn't solve everything. A bigger change in the new API is that the function mvVISLAM_Initialize has a bunch more new parameters that I don't know how to get (or how the developers expect us to get those). Seems like they should update this repository to follow the new API updates. 

BTW, would you still have mv_0.9.1? Its not available for download anymore, so I was wondering if I could roll back to an old update in the meantime.

**Comment by hoangthien94** [comment]
@ericjohnson97 Thanks for your reply. 
Here is the link for [mv_0.9.1](https://we.tl/TMSx8RqL3m). 

I also had not found a way to workaround this. But I found that the package [snap_vio](https://github.com/ATLFlight/snap_vio) works fine with `mv_1.1.9` so I can still play around with mvVISLAM in ros, which I what I wanted. 

I will close the issue for now.
